### ISSUE TITLE
NuProj and non-NuProj dependencies mixing bug

### ISSUE THREAD

**Issue by kovalikp** [terrajobst/nuproj#12]
Dependencies from NuProj ProjectReference do not have TargetFramework metadata.
Dependencies from non-NuProj ones always have.

This means NuProj depencency will not be resolved, because package definition will contain:
```xml
<dependencies>
  <group>
	<dependency id="NuprojDepenency" version="1.0.0" />
  </group>
  <group targetFramework="net40">
	<dependency id="CsprojDependency" version="1.0.0" />
  </group>
<dependencies>
```

PS: GetPackageIdentity need to be changed or replaced. I'll have a look at it.

**Comment by terrajobst** [comment]
Fixed with 954eefe933fd809315019fb9f4ce8bcfafbee7d4.
