### ISSUE TITLE
NuProj doesn't build referenced NuProj

### ISSUE THREAD

**Issue by AArnott** [terrajobst/nuproj#32]
When one NuProj references another via a ProjectReference, and the referencing one is built at the command line, it doesn't cause the referenced one to build.

Amazingly, no build error is produced. But since the resulting NuPkg file is incomplete without its dependency NuPkg also built, the result _should_ be to produce both by building the referenced NuProj projects.

**Comment by terrajobst** [comment]
@AArnott The `CopyLocal` behavior is an interesting one. I've filed issue #55. This allows us to close this independently.
