### ISSUE TITLE
Empty NuProj fails to build

### ISSUE THREAD

**Issue by davkean** [terrajobst/nuproj#47]
A empty NuProj fails to build:

Repro:
1. Create a new NuGet project
2. Remove Readme.txt
3. Build

@Expected: For the project to build
@Actual: The project fails to build with:

Could not find file 'NuGetPackage4\NuGetPackage4\obj\Debug\NuGetPackage4.nuspec'.	

While I understand this is not the expected result (what's the point of an empty package?), this took a bit to diagnose as I was attempting to customize the building of the project, and thought that I broke something. Rolled back my changes and realized it was just that it was empty.

**Comment by terrajobst** [comment]
Agreed.

**Comment by terrajobst** [comment]
No longer repros. There was probably an issue where the .nuspec file wasn't generated because no dependencies were found. The build now fails when calling `nuget.exe pack`:

> NuProj.targets(507,5): error : Failed to build package. Ensure 'C:\Users\Immo\Documents\Visual Studio 2013\Projects\NuG etPackage1\NuGetPackage1\obj\Debug\NuGetPackage1.nuspec' includes assembly files. For help on building symbols package, visit http://docs.nuget.org/.

**Comment by terrajobst** [comment]
After merging in #42 the error message got even better:

> Cannot create package that has no dependencies nor content.

See commit eb6a81a08ce6ec16a482167d947e9576c6c11f75 for more details why the error message changed.
