### ISSUE TITLE
Adding an existing file defaults to "None" 

### ISSUE THREAD

**Issue by davkean** [terrajobst/nuproj#48]
When adding a new file to a NuProj, the build action defaults to "None" which means it does not get included. A better default will be "Content" to avoid surprises

**Repro:**
1. Create a new Nuproj
2. Right-click on project and choose Add -> Existing File
3. Browse to an existing file
4. Click OK
5. Right the file and choose Properties

**Expected:** Build action to be set to "Content"
**Actual:** Build action is set to "None"

**Comment by terrajobst** [comment]
Thanks. I'll fix this in the VS integration.

**Comment by terrajobst** [comment]
Fixed with ac25018278f68a8ed381f2028ec2c9bafb762380 (which isn't on GitHub yet).
