### ISSUE TITLE
Merging NuGet Package Issue

### ISSUE THREAD

**Issue by StephenErstad** [terrajobst/nuproj#49]
When referencing two different projects that both depend on the same NuGet package, I get the following error:

> "'NuProj Project Name' already has a dependency defined for 'Common NuGet Package'."

Both projects are using the same versions of the NuGet package (and their dependencies).  Both projects require mutually exclusive packages.

One project has a dependency on the other project.

**Comment by terrajobst** [comment]
Thanks for reporting. I'll take a look.

**Comment by terrajobst** [comment]
No longer repros with the latest source. Was probably already fixed with #33.
