### ISSUE TITLE
Admin installs of NuProj fail with 2203

### ISSUE THREAD

**Issue by davkean** [terrajobst/nuproj#50]
### Repro:

```
 msiexec /log msi.log /a "C:\Temp\NuProj.msi" TARGETDIR=C:\Temp
```

### Expected

Contents to be installed to `C:\Temp`

### Actual

The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203.

**Comment by davkean** [comment]
Log is here: https://gist.github.com/davkean/a83900915b0baeb03465

**Comment by terrajobst** [comment]
Doesn't repro with either 0a9dee1e0ae206d043c33bbc7f140218868c50ad nor with the latest build of the fork that contains the VS integration. Was probably fixed inadvertently ealier.

**Comment by davkean** [comment]
This is still an issue with the latest build. I thought it might have something to do with the "Mark of the web", but even _Properties_ -> _Unblock_ did not fix the issue.

**Comment by davkean** [comment]
I've also checked permissions on Temp folder, but it didn't help.

**Comment by kovalikp** [comment]
It's not possible to perform administrative install into same directory as the one containing the original .msi file. Administrative install will try to generate new .msi into the target directory, in your case trying to overwrite the one it's currently reading.

Just select different directory for your administrative install and it should work. At least it did for me.

**Comment by davkean** [comment]
Ha - funnily, over the many years of doing that I've never run into this before. Thanks!
