### ISSUE TITLE
Exclude automatic project reference dependency (it's already defined as package dependency)

### ISSUE THREAD

**Issue by AndirNotes** [terrajobst/nuproj#79]
Use case:
I have VS solution with several projects and packages. e.g.:
* Project1.csproj (No references, Output: Project1.dll)
* Project1.NuGetPackage.nuproj (References Project1, Output: Project1.nupkg)
* Project2.csproj (References Project1, Output: Project2.dll)
* Project2.NuGetPackage.nuproj (References Project2, Output: Project2.nupkg)

Project2 references Project1, but Project2.NuGetPackage also defines an explicit dependency on Project1.NuGetPackage (via <Dependency> Item>).

After the build Project2.nupkg contains Project2.dll and Project1.dll (automatically determined as runtime needed) and explicit dependency on package Project1.nupkg.

It would be nice to have a way to exclude Project1.dll from the package Project2.nupkg.

**Comment by williamb1024** [comment]
Add a reference to `Project1.NuGetPckage.nuproj` from `Project2.NuGetPackage.nuproj`. That should cause Project2.nupkg to reference Project1.nupkg rather than import Project1.dll.

**Comment by AndirNotes** [comment]
Oh, great! I wasn't think to do that. This certainly solves the issue.
